ARG UBUNTU_VERSION=20.04
ARG CUDA_VERSION=11.3.1
ARG CUDNN_VERSION=8

FROM nvidia/cuda:${CUDA_VERSION}-cudnn${CUDNN_VERSION}-runtime-ubuntu${UBUNTU_VERSION}
RUN apt-get update && apt-get install --no-install-recommends -y gcc libc6-dev git

WORKDIR /workdir

COPY requirements.txt requirements.txt
COPY pyproject.toml pyproject.toml
RUN pip install --default-timeout=1000 --compile .

COPY . /workdir/

ENTRYPOINT ["jina", "executor", "--uses", "config.yml"]